# Config dikodekan secara otomatis via nginx.js
server {
    listen 1400;
    server_name _;

    # Logging
    access_log /var/log/nginx/hrd_survey_access.log;
    error_log /var/log/nginx/hrd_survey_error.log;

    # Dynamic Proxy Headers
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Backend API Routing (/api/ atau /api)
    location /api {
        proxy_pass http://127.0.0.1:1402;
    }

    # Frontend App Routing (Default /)
    location / {
        proxy_pass http://127.0.0.1:1401/;
    }
}
